### ISSUE TITLE
Autocomplete on <option> content

### ISSUE THREAD

**Issue by sdgluck** [dfmcphee/combobox#1]
I was a bit confused when I used the demo that it doesn't filter results by what is displayed in the dropdown menu, but rather the `value` of an `<option>`.

Filtering also by the contents of the `<option>`s would be neat.

Nice module :-)

**Comment by maxmagee** [comment]
I agree with @sdgluck. The end-user does not know what the actual 'values' are for the options they need to choose from, nor should they. Instead of filtering on the values, you should be filtering on the contents of the options as he suggested. Cool idea though. 

Bonus points for making it configurable to do either or both.

**Comment by dfmcphee** [comment]
Good suggestion. For now I made it match on both value and option content.
